// src/components/design/layout/canvas/children/background.tsx
import { getPositionInfoFromOptions } from '../helper.tsx'

export function createCanvasChildBackground(options) {
    // 处理布局
    const {
        containerStyle: _containerStyle,
        style: _style
    } = getPositionInfoFromOptions(options.position)

    const containerStyle = {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: options.zIndex,
        ..._containerStyle
    }

    const style = {
        width:options.width + '%',
        height: options.height + '%',
        background: options.backgroundColor,
        ..._style
    }

    if(options.backgroundImage){
        style.backgroundImage = `url(${options.backgroundImage.url})`
    }


    return <div style={containerStyle}>
        <div style={style}></div>
    </div>
}

// src/components/design/layout/canvas/children/background/index.tsx
import { canvasStickerOptions, updateRenderingCanvas } from '../../index.tsx'
import { getPositionInfoFromOptions, formatToNativeSizeString, formatToNativeSizeOption, parseTextShadowOptionsToCSS, formatSizeOptionToPixelValue, createFilterFromOptions, createTransformString } from '../../helper.tsx'
import { defineComponent, ref, onUpdated, onMounted } from 'vue'
import Utils from '@/common/utils'
import { createFilterDefaultOptions, createTransformDefaultOptions, createPositionDefaultOptions, createBasicDefaultOptions } from "../defaultOptions.tsx";

import { queryCustomBackgroundById } from './builtIn/index.ts'

import { onBeforeReturnRender,onCanvasChildSetup } from '../commonHooks.ts';

/**
*/


export const createDefaultCanvasChildBackgroundOptions = () => {
    const canvasUnit = canvasStickerOptions.value.unit
    return {
        type: 'background',
        ...createBasicDefaultOptions(),
        position: createPositionDefaultOptions(canvasUnit),

        width: {
            value: 100,
            unit: 'vw'
        },
        height: {
            value: 100,
            unit: 'vh'
        },
        backgroundColor: {
            color: '#000',
            type: 'pure'
        },
        transform: createTransformDefaultOptions(canvasUnit),
        filter: createFilterDefaultOptions(canvasUnit),
        zIndex: 0,
        customBackground: {
            id: '',
            label: ''
        },
        clipPath:null
    }
}

export const Background = defineComponent({
    props: {
        options: null
    },
    setup(props, ctx) {

        const targetEl = ref()


        onCanvasChildSetup({
            targetEl: targetEl,
            options: props.options,
            props: props
        })


        return () => {

            // 处理布局
            const {
                containerStyle: _containerStyle,
                style: _style
            } = getPositionInfoFromOptions(props.options.position)

            const containerStyle = {
                width: '100%',
                height: '100%',
                position: 'absolute',
                top: 0,
                left: 0,
                ..._containerStyle
            }

            const style = {
                width: formatToNativeSizeString(props.options.width),
                height: formatToNativeSizeString(props.options.height),
                background: props.options.backgroundColor.color,
                flexShrink: 0,
                transform: createTransformString(props.options.transform),
                filter: createFilterFromOptions(props.options.filter),
                zIndex: props.options.zIndex,
                ..._style
            }

            var renderSlot


            if (props.options.customBackground.id) {
                // 根据背景id寻找背景
                let customeBackground = queryCustomBackgroundById(props.options.customBackground.id)
                if (customeBackground.renderSlot) {
                    renderSlot = customeBackground.renderSlot()
                }
            }


            onBeforeReturnRender({
                style,
                options: props.options
            })


            return <div style={containerStyle}>
                <div ref={targetEl} style={style}>
                    {renderSlot}
                </div>
            </div>
        }
    }
})

export function createCanvasChildBackground(options) {
    return <Background options={options} onVnodeUpdated={updateRenderingCanvas} onVnodeMounted={updateRenderingCanvas}></Background>
}
